### ISSUE TITLE
Input items are deleted if you close the GUI before removing them manually

### ISSUE THREAD

**Issue by Ridanisaurus** [brckts/Portable-Stonecutter#2]
Version: 1.0

Description: 
If I open the GUI, place a stack there, and then close the GUI without taking anything out, the input is deleted instead of it returning to the player's inv.

**Comment by brckts** [comment]
fixed by https://github.com/brckts/Portable-Stonecutter/commit/3550b1da873008f491e68226bf666293356cb0a8
