### ISSUE TITLE
Flattening Recipe doesn't work if redstone is stacked up

### ISSUE THREAD

**Issue by MuteTiefling** [brckts/Portable-Stonecutter#4]
Forge: 35.1.13
Mod: portable_stonecutter-1.1.1

Drop the pressure plate, stone cutter, and 2 redstone as a stack (ctrl + throw) and the recipe won't complete. It only completes if the two redstone dust were dropped individually and the anvil falls on them before they have a chance to group up into a stack.

**Comment by brckts** [comment]
thanks for the report, I can't seem to replicate it on version 1.1.1, which version were you using when noticing the issue ?

**Comment by MuteTiefling** [comment]
I'll try again and let you know. I apologize, I thought I had left the mod and forge version in the ticket.

**Comment by MuteTiefling** [comment]
Here, I was able to reproduce it in 1.1.1.

https://streamable.com/8odzjh

I think it may actually be the height, however. You'll see my first two attempts failed, but when I dropped the anvil from only 1 block, it worked.

**Comment by brckts** [comment]
yes it is indeed the height, a fault on documentation on my part. As of 1.2.1 you'll be able to drop from any height.
