### ISSUE TITLE
[Server Crash] Exception in server tick loop

### ISSUE THREAD

**Issue by Ridanisaurus** [brckts/Portable-Stonecutter#6]
Server crashed when clicking `All` in the GUI. 

Log: https://gist.github.com/Ridanisaurus/ad4eaef7215c0f2d167a3858f3eddda2

**Comment by brckts** [comment]
Last push should've fixed it, can't test on a server until tomorrow though so I'll update you then.

**Comment by brckts** [comment]
Managed to test
