### ISSUE TITLE
Server hangs after clicking 'All' in the GUI

### ISSUE THREAD

**Issue by DarkAngel22579** [brckts/Portable-Stonecutter#7]
**Version: 1.3.1**
Playing on the E6 official server.

Clicking ```All``` in the GUI didn't work, but I was still able chisel blocks normally. The server hangs after closing the GUI.

Possibly related to https://github.com/brckts/Portable-Stonecutter/issues/6

**Comment by brckts** [comment]
I doubt it is related to #6, I sanitized the craftAll method a bit more but I am still unable to reproduce your issue :/

**Comment by DarkAngel22579** [comment]
**Update**

I can now consistently make the server hang after pressing ```All```. Happens both in single-player and on a locally hosted server.

In the videos attached, you can see the chiseled stone either: 
1. Flicker into my inventory before returning to the stonecutter.
2. Return to the unselected state without flickering into my inventory.
3. Get chiseled normally, and the server then hangs after closing the GUI.

Something to note is that I'm holding down shift the entire time while in the stonecutter GUI. I can't replicate this if I only press shift when moving the blocks.

I also wasn't able to generate a crash report from any of these.

https://imgur.com/a/Ns5rRUd

**Comment by brckts** [comment]
Ah yes, the shift part was the issue, if you shift clicked a recipe you hadn't selected beforehand it would select and lock on the client but just lock on the server, which explains the flickering (client trying to perform a craftAll and server reverting it), the crafting being constantly running and reverted might explain why it hanged (previous craftAll implementation ran until no ingredients were left but I changed it to something saner in 1.3.2).

**Comment by brckts** [comment]
thanks for all the investigation, I would have never tried doing it all while holding shift

**Comment by DarkAngel22579** [comment]
Np dude, happy to help.

I also managed to crash the E6 server without using ```All```, but I couldn't replicate that.
Hopefully its related and this fixes it too.

**Comment by brckts** [comment]
I sure hope so, PSC has already crashed E6 a few to many times given its minuscule scale
